// RootLayout.tsx
import "../styles/main.scss";
import 'react-responsive-carousel/lib/styles/carousel.min.css'; 
import type { Metadata } from "next";
import SideBar from "../components/sideBar";

export const metadata: Metadata = {
  title: "Teach Idioms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="appContainer">
        <SideBar />
        <div className="contentArea">
          {children}
        </div>
      </div>
    </>
  );
}
